FROM node:22-slim AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:22-slim AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_IDENTITY_PLATFORM_API_KEY
ARG NEXT_PUBLIC_IDENTITY_PLATFORM_AUTH_DOMAIN
ARG NEXT_PUBLIC_IDENTITY_PLATFORM_PROJECT_ID
ARG NEXT_PUBLIC_IDENTITY_PLATFORM_APP_ID
ENV NEXT_PUBLIC_IDENTITY_PLATFORM_API_KEY=$NEXT_PUBLIC_IDENTITY_PLATFORM_API_KEY
ENV NEXT_PUBLIC_IDENTITY_PLATFORM_AUTH_DOMAIN=$NEXT_PUBLIC_IDENTITY_PLATFORM_AUTH_DOMAIN
ENV NEXT_PUBLIC_IDENTITY_PLATFORM_PROJECT_ID=$NEXT_PUBLIC_IDENTITY_PLATFORM_PROJECT_ID
ENV NEXT_PUBLIC_IDENTITY_PLATFORM_APP_ID=$NEXT_PUBLIC_IDENTITY_PLATFORM_APP_ID
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
EXPOSE 8080
CMD ["node", "server.js"]
